---
- name: Crear issue en Redmine usando la API REST
  hosts: localhost
  gather_facts: no
  vars:
    redmine_url: "http://redmine.apps.ocp4.minsal.devqa"  # <-- cambia por tu URL
    api_key: "{{ API_KEY }}"                         # <-- reemplaza con tu API Key
    project_id: "Ansible"                            # <-- ID o identificador del proyecto
    issue_subject: "{{ ticket_subjet }}"
    issue_description: "{{ ticket_content }}"
    priority_id: "{{ prioridad }}"                              # 1 = Low, 4 = Normal, etc.

  tasks:
    - name: Crear un ticket en Redmine
      uri:
        url: "{{ redmine_url }}/issues.json"
        method: POST
        validate_certs: no 
        headers:
          Content-Type: "application/json"
          X-Redmine-API-Key: "{{ api_key }}"
        body_format: json
        body: |
          {
            "issue": {
              "project_id": "{{ project_id }}",
              "subject": "{{ issue_subject }}",
              "description": "{{ issue_description }}",
              "priority_id": "{{ priority_id }}"
              }
           }   
        status_code: 201
       # validate_certs: no  # 👈 esta línea desactiva la verificación del certificado SSL
        return_content: yes
      register: redmine_response

    - name: Mostrar respuesta de Redmine
      debug:
        var: redmine_response.json
