---
- name: cargar certificado
  hosts: "{{ host_name }}"
  gather_facts: false

  tasks:
    - name: mostrar certificado
      ansible.builtin.debug:
        msg: "{{ cert_data }}"
    - name: Render out the certificate file somewhere
      copy:
        content: "{{ cert_data }}"
        dest: /opt/server_certificates/certificate.cer
    - name: carga certificado a la keystore
      command: keytool -import -alias mykey -file /opt/server_certificates/certificate.cer -keystore /opt/server_certificates/y0detectta05.jks -storepass changeit -keypass changeit
