---
- name: create CSR v2
  hosts: "{{ host_name }}"
  become: yes

  tasks:
#    - name: Generar directorio para CSR
#      file:
#        path: /opt/server_certificates//opt/server_certificates/csr.pem
#        state: directory
#        mode: 0755
    - name: crear backup de llave original
      command: mv /opt/server_certificates/y0detectta03.jks /opt/server_certificates/y0detectta03.jks.bak
      
#    - name: borado 1
#      command: rm -rf  /opt/server_certificates/y0detectta05.jks 
      
#    - name: Generar keystore
#      command: keytool -genkeypair -alias mykey -keyalg RSA -keystore /opt/server_certificates/y0detectta05.jks -storepass bisabisa -dname "CN=y0detectta04, OU=Banco , O=Banco Bisa, L=La PAZ, ST=BO,C=BO"
#      args:
#        creates: /opt/server_certificates/y0detecta05.jks
    - name: Generar CSR
      command: keytool -certreq -alias mykey -keystore /opt/server_certificates/y0detectta03.jks -file /opt/secert.csrrver_certificates/cert.csr -storepass changeit -keypass changeit
      
    - name: Mostrar CSR
      command: cat /opt/server_certificates/cert.csr
      register: csr_output

    - name: Imprimir CSR generado
      debug:
        var: csr_output.stdout_lines
    - name: set stat para el certificado
      ansible.builtin.set_stats:
        data: 
          csr_data: "{{ csr_output.stdout }}"
