---
- name: create CSR v2
  hosts: "{{ host_name }}"
  become: yes

  tasks:
#    - name: Generar directorio para CSR
#      file:
#        path: /opt/server_certificates/
#        state: directory
#        mode: 0755
    - name: crear backup de llave original
      command: cp /opt/server_certificates/y0detectta03.jks /opt/server_certificates/y0detectta03.jks.bak

    - name: Generar keystore
      command: keytool -genkeypair -alias mykey -keyalg RSA -keystore /opt/server_certificates/y0detecta05.jks -storepass changeit -subj "/C=BO/ST=Denial/L=LAPAZ/O=Dis/CN=$(hostname)"
      args:
        creates: /opt/server_certificates/y0detecta05.jks
    - name: Generar CSR
      command: openssl req -new -key /opt/server_certificates/private.key -out /opt/server_certificates/csr.pem -subj "/C=BO/ST=Denial/L=LAPAZ/O=Dis/CN=$(hostname)"
      
    - name: Mostrar CSR
      command: cat /opt/server_certificates/csr.pem
      register: csr_output

    - name: Imprimir CSR generado
      debug:
        var: csr_output.stdout_lines
    - name: set stat para el certificado
      ansible.builtin.set_stats:
        data: 
          csr_data: "{{ csr_output.stdout }}"
