---
- name: Deploy authorized_keys from template
  hosts: all
  become: yes
  tasks:


    - name: Generate authorized_keys using template
      ansible.builtin.template:
        remote_src: "https://raw.githubusercontent.com/Felipe-Henriquez-Gonzalez/desarrollo/main/template/authorized_keys.jn2"
        dest: "/home/ansible/.ssh/authorized_keys"
        owner: ansible
        group: ansible
        mode: '0600'

    - name: Ensure correct permissions on .ssh directory
      ansible.builtin.file:
        path: "/home/ansible/.ssh"
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'
