---
- name: Install required packages
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name:
          - wget
          - git-core
          - rsync
          - vim
          - ansible-core
        state: present
