---
- name: Registrar sistema RHEL con subscription-manager
  hosts: all
  become: true
  vars:
    rhsm_username: "{{ tu_usuario }}"  # Cambia esto por tu usuario de Red Hat
    rhsm_password: "{{ tu_contrasena }}"  # Cambia esto por tu contraseña
  tasks:
    - name: Asegurar que subscription-manager está instalado
      ansible.builtin.yum:
        name: subscription-manager
        state: present
    - name: Suscribir rhel
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true
