---
- name: Crear Firma certificado Windows 
  hosts: "{{win_host}}"
  gather_facts: false

  tasks:
    - name: Make sure the response files don't exist, will turn up an error if they're there
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - c:\a.p12
        - c:\cert.csr
      
    - name: create keystore
      ansible.windows.win_command:
        cmd: keytool -genkey -alias server -validity 365 -keyalg RSA -keystore c:/a.p12 -dname "CN={{win_host}}, OU=Banco , O=Banco Bisa, L=La PAZ, ST=BO,C=BO" -storepass bisabisa
      failed_when: false

    - name: create csr
      ansible.windows.win_command:
        cmd: keytool -certreq -alias server   -keystore c:/a.p12 -file c:/cert.csr -storepass bisabisa
      failed_when: false
   
    - name: list C disk
      ansible.windows.win_shell: dir c:\
      
    - name: Make sure the response files don't exist, will turn up an error if they're there
      ansible.windows.win_file:
        path: "{{ item }}"
        state: present
      loop:
        - c:\a.p12
        - c:\cert.csr
      

#    - name: Imprimir CSR generado
#      ansible.builtin.debug:
#        var: csr_output.stdout_lines
        
#    - name: set stat para el certificado
#      ansible.builtin.set_stats:
#        data: 
#          csr_data: "{{ csr_output.stdout }}"
