---
- name: Validate windows server
  hosts: windows
  gather_facts: false

  tasks:
  #  - name: Ensure WinRM is enabled
  #    win_shell: echo true
  #    register: result
  #    changed_when: false
    - name: Show csr
      ansible.builtin.debug:
        msg: "{{ csr_data }}"

    - name: Render out the CSR file somewhere
      ansible.windows.win_copy:
        content: "{{ csr_data }}"
        dest: c:\candidate.csr

    - name: List out the certification authorities in the AD
      ansible.windows.win_shell: certutil -config - -ping

        
  #  - name: Generate Self-Signed Certificate
  #    win_shell: |
  #      $cert = New-SelfSignedCertificate -DnsName "x0axon01" -CertStoreLocation "Cert:\LocalMachine\My"
  #      $certThumbprint = $cert.Thumbprint
  #      $certThumbprint
  #    register: cert_result

#
 
  #  - name: Submit Certificate Request
  #    win_shell: |
  #      $certThumbprint = "{{ cert_result.stdout }}"
  #      Submit-CertificateRequest -Thumbprint $certThumbprint -CertStoreLocation "Cert:\LocalMachine\My"
  #    when: cert_result.stdout is defined
