---
- name: Validate windows server
  hosts: windows
  gather_facts: false

  tasks:
  #  - name: Ensure WinRM is enabled
  #    win_shell: echo true
  #    register: result
  #    changed_when: false
    - name: Show csr
      ansible.builtin.debug:
        msg: "{{ csr_data }}"

    - name: Render out the CSR file somewhere
      ansible.windows.win_copy:
        content: "{{ csr_data }}"
        dest: c:\candidate.csr

    - name: List out cert authorities
      ansible.windows.win_command:
        cmd: certutil -ping z0cert04.grupobisa.net
      failed_when: false

    - name: Make sure the response files don't exist, will turn up an error if they're there
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - c:\outfile.cer
        - c:\outfile.rsp

    - name: Sign the Certificate
      ansible.windows.win_command:
        cmd: >-
          certreq.exe -q 
          -attrib "CertificateTemplate:webserver"  
          -Submit 
          c:\candidate.csr c:\outfile.cer

    - name: Get the signed cert
      ansible.windows.win_shell: type c:\outfile.cer
      register: contenido_cer

    - name: Print the signed cert
      ansible.builtin.debug:
        var: contenido_cer.stdout  

    - name: List the directory
      ansible.windows.win_shell: dir c:\


  #  - name: Generate Self-Signed Certificate
  #    win_shell: |
  #      $cert = New-SelfSignedCertificate -DnsName "x0axon01" -CertStoreLocation "Cert:\LocalMachine\My"
  #      $certThumbprint = $cert.Thumbprint
  #      $certThumbprint
  #    register: cert_result

#
  #  - name: Submit Certificate Request
  #    win_shell: |
  #      $certThumbprint = "{{ cert_result.stdout }}"
  #      Submit-CertificateRequest -Thumbprint $certThumbprint -CertStoreLocation "Cert:\LocalMachine\My"
  #    when: cert_result.stdout is defined
