---
- name: Cambiar la contraseña del usuario juan similar a passwd
  hosts: servidores_linux
  become: yes
  vars:
    usuario_objetivo: juan
    nueva_clave: "NuevaPassword123"
  
  tasks:
    - name: Cambiar contraseña del usuario "{{ usuario_objetivo }}"
      ansible.builtin.user:
        name: "{{ usuario_objetivo }}"
        password: "{{ nueva_clave | password_hash('sha512') }}"
        update_password: always
