- name: Test de conectividad Cisco C8000V
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Verificar conectividad con "show version"
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources: all
      register: output

    - name: Mostrar resultado
      debug:
        var: output.stdout_lines
