---
- name: Cisco show version example
  hosts: cisco
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Create vlan10
      cisco.ios.ios_vlans:
        config:
          - name: vlan10
            vlan_id: 10
        state: merged

  
