---
- name: Cisco show version example
  hosts: cisco
  gather_facts: true

  vars: # for execution environment
  
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:

    - name: Ejecutar comando 'show running-config'
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: vlan_info

    - name: show running-config
      debug:
        var: vlan_info
    - name: pasar el dato a la siguiente etapa del workflow
      ansible.builtin.set_stats:
        data:
          vlan_data: "{{ vlan_info }}"
