- name: Test de conectividad Cisco C8000V
  hosts: cisco
  gather_facts: false

  tasks:
    - name: Enable NETCONF
      connection: ansible.netcommon.network_cli
      cisco.iosxr.iosxr_netconf:
      
    - name: Gather all network resource and minimal legacy facts [Cisco IOS]      
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources: all

    - name: Verificar conectividad con "show version"
      cisco.iosxr.iosxr_command:
        commands: 
          - show version
      register: output

    - name: Mostrar resultado
      debug:
        var: output.stdout_lines
