- name: Test de conectividad Cisco C8000V
  hosts: cisco
    delegate_to: localhost
  tasks:

    - name: Verificar conectividad con "show version"
      cisco.iosxr.iosxr_command:
        commands: 
          - show version
      register: output

    - name: Mostrar resultado
      debug:
        var: output.stdout_lines
