- name: Test de conectividad Cisco C8000V
  hosts: cisco
  gather_facts: no
  ansible_connection: ansible.netcommon.network_cli
  tasks:
    - name: Verificar conectividad con "show version"
      cisco.iosxr.iosxr_command:
        commands: show version
        wait_for: result[0] contains IOS-XR
      register: output

    - name: Mostrar resultado
      debug:
        var: output.stdout_lines
