---
- name: Cisco show version example
  hosts: cisco
  gather_facts: true

  vars: # for execution environment
  
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Crear VLAN 10 con nombre VLAN_10
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 10
            name: VLAN_10
            state: active
            shutdown: disabled
            
    - name: Obtener VLANs configuradas
      cisco.ios.ios_vlans:
        state: gathered
      register: vlan_info

    - name: Mostrar información de VLANs
      debug:
        var: vlan_info
    - name: pasar el dato a la siguiente etapa del workflow
      ansible.builtin.set_stats:
        data:
          vlan_data: "{{ vlan_info }}"
