---
- name: Cisco create interface
  hosts: cisco
  gather_facts: true

  vars: # for execution environment
  
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
      - name: Configurar interfaz GigabitEthernet1/0/10
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1/0/10
            description: "Puerto de usuarios"
            enabled: true
            mtu: 1500
        state: merged

    - name: Obtener interfaces configuradas
      cisco.ios.ios_interfaces:
        state: gathered
      register: vlan_info

    - name: Mostrar información de interfaces
      debug:
        var: vlan_info
    - name: pasar el dato a la siguiente etapa del workflow
      ansible.builtin.set_stats:
        data:
          vlan_data: "{{ vlan_info }}"
