---
- name: Cisco show version example
  hosts: cisco
  gather_facts: false

  vars: # for execution environment
  
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:


    - name: Crear interfaces loopback
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback0
            description Loopback de gestión 0
            ip address 10.0.0.1 255.255.255.255
            no shutdown
          - name: Loopback1
            description Loopback de gestión 1
            ip address 10.0.1.1 255.255.255.255
            no shutdown
          - name: Loopback2
            description Loopback de gestión 2
            ip address 10.0.2.1 255.255.255.255
            no shutdown

    - name: Crear VLAN 325
      cisco.ios.ios_vlans:
        config:
          - name: VLAN_325
            vlan_id: 325
            state: active
            shutdown: disabled
            remote_span: true

    - name: Crear VLAN 440
      cisco.ios.ios_vlans:
        config:
          - name: VLAN_440
            vlan_id: 440
            state: active
            shutdown: disabled
            remote_span: true

    - name: Crear VLAN 660
      cisco.ios.ios_vlans:
        config:
          - name: VLAN_660
            vlan_id: 660
            state: active
            shutdown: disabled
            remote_span: true
