---
- name: Cisco show version example
  hosts: cisco
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:

    - name: Crear interfaces loopback
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback0
            description: Loopback de gestión 0
            enabled: true
          - name: Loopback1
            description: Loopback de gestión 1
            enabled: true
          - name: Loopback2
            description: Loopback de gestión 2
            enabled: true
        state: merged

    - name: Crear VLANs
      cisco.ios.ios_vlans:
        config:
          - name: VLAN325
            vlan_id: 325
          - name: VLAN440
            vlan_id: 440
          - name: VLAN660
            vlan_id: 660
        state: merged
