---
- name: Publicar página demo en Apache desde Git
  hosts: "{{ target_host }}"
  become: true

  vars:
    git_repo_url: "https://github.com/Felipe-Henriquez-Gonzalez/demoapache.git"
    apache_document_root: "/var/www/html"

  tasks:
    - name: Instalar Apache y Git en RHEL
      ansible.builtin.dnf:
        name:
          - httpd
          - git
        state: present

    - name: Habilitar e iniciar Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Limpiar contenido anterior del DocumentRoot
      ansible.builtin.file:
        path: "{{ apache_document_root }}"
        state: absent

    - name: Crear DocumentRoot
      ansible.builtin.file:
        path: "{{ apache_document_root }}"
        state: directory
        owner: apache
        group: apache
        mode: "0755"

    - name: Clonar página desde Git en la ruta default de Apache
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ apache_document_root }}"
        version: main
        force: true

    - name: Ajustar permisos del sitio
      ansible.builtin.file:
        path: "{{ apache_document_root }}"
        owner: apache
        group: apache
        recurse: true


    - name: Reiniciar Apache
      ansible.builtin.service:
        name: httpd
        state: restarted
