---
- name: Actualiza rhel a la ultima version
  hosts: "{{ _hosts }}"
  gather_facts: false
  become: true

  tasks:
    - name: actualiza rhel a la ultima version 
      ansible.builtin.dnf:
        name: "*"
        state: latest
