---
- name: Actualiza rhel a la ultima version
  hosts: all
  gather_facts: false

  tasks:
    - name: actualiza rhel a la ultima version 
      ansible.builtin.dnf:
        name: "*"
        state: latest
