- name: Play Name
  hosts: localhost
  vars_files:
    - credentials.yml
  vars:
    corp_name: "{{ corp }}"
  gather_facts: false
  tasks:
    - name: Get Organization Networks
      cisco.meraki.networks_info:
        organizationId: "{{ org_id }}"
      register: result
    - name: Filter networks with "wireless" productTypes
      ansible.builtin.set_fact:
        filtered_networks:
          "{{ result.meraki_response | selectattr('productTypes',
          'contains', 'wireless') | list }}"

    - name: Create Mobile/PSK SSID
      cisco.meraki.networks_wireless_ssids:
        state: present
        enabled: true
        name: "{{ corp_name }}-legacy"
        networkId: "{{ item.id }}"
        number: 2
        ipAssignmentMode: Bridge mode
        defaultVlanId: 200
        useVlanTagging: true
        authMode: psk
        encryptionMode: wpa
        psk: SuperSecretPreSharedKey
      loop: "{{ filtered_networks }}"
      loop_control:
        label: "{{ item.id }}"
    - name: Create Guest SSID
      cisco.meraki.networks_wireless_ssids:
        state: present
        enabled: true
        name: "{{ corp_name }}-Guests"
        networkId: "{{ item.id }}"
        number: 3
        ipAssignmentMode: Bridge mode
        defaultVlanId: 300
        useVlanTagging: true
        authMode: open
        splashPage: Click-through splash page
      loop: "{{ filtered_networks }}"
      loop_control:
        label: "{{ item.id }}"
