- name: crea Red
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Crear Red Meraki
      cisco.meraki.networks:
        state: present
        organizationId: "{{ org_id }}"
        meraki_api_key: "{{ var_api_key }}"
        name: "{{ nombre_red }}"
        notes: Creado_con_ansible
        productTypes:
          - switch
          - appliance
          - wireless
        timeZone: Australia/Sydney
