---
- name: Get information from Meraki console
  hosts: all
  tasks:
    - name: Get networks
      cisco.meraki.meraki_networks:
        auth_key: "{{ _auth_key_ }}"
        state: query
      register: networks
   
