- name: Administrar Cisco Meraki con Ansible
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Obtener información de las redes en la organización Meraki
      cisco.meraki.networks_info:
        organization_id: "{{ org_id }}"
        meraki_api_key: "{{ var_api_key }}"
        state: query
      register: meraki_networks

    - name: Mostrar redes disponibles
      debug:
        var: meraki_networks
