- name: Play Name
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get all organizations _devices
      cisco.meraki.organizations_devices_info:
        meraki_suppress_logging: true
        organizationId: "{{ org_id }}"
        meraki_api_key: "{{ api_key }}"
        total_pages: -1
      register: org_devices
    - name: Show All Devices
      ansible.builtin.debug:
        msg: "{{ org_devices }}"

    - name: pasar el dato a la siguiente etapa del workflow
      ansible.builtin.set_stats:
        data:
          vlan_data: "{{ org_devices }}"
   
